const stays = [
  {
    slug: "bukchon-hanok-hideout",
    title: "북촌 감성 한옥 스테이",
    summary: "마당과 다도를 즐길 수 있는 조용한 도심 한옥",
    location: "서울, 종로구",
    city: "서울",
    district: "종로구",
    country: "대한민국",
    distance: "경복궁까지 도보 11분",
    pricePerNight: 128000,
    rating: 4.93,
    reviewCount: 214,
    badge: "게스트 선호",
    gradient: "linear-gradient(135deg, #f7cab5 0%, #f9f0d9 100%)",
    category: "한옥",
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    petFriendly: false,
    keywords: ["서울", "한옥", "북촌", "종로", "전통", "도심"],
    availability: {
      startDate: "2026-04-20",
      endDate: "2026-06-30",
    },
  },
  {
    slug: "hanriver-rooftop-studio",
    title: "한강이 보이는 루프탑 스튜디오",
    summary: "야경과 러닝 코스를 함께 누리는 성수 감성 숙소",
    location: "서울, 성동구",
    city: "서울",
    district: "성동구",
    country: "대한민국",
    distance: "성수역까지 도보 8분",
    pricePerNight: 154000,
    rating: 4.95,
    reviewCount: 187,
    badge: "인기",
    gradient: "linear-gradient(135deg, #9ec5fe 0%, #fef9d7 100%)",
    category: "전망 좋은 숙소",
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    petFriendly: true,
    keywords: ["서울", "한강", "루프탑", "성수", "야경", "도심"],
    availability: {
      startDate: "2026-04-25",
      endDate: "2026-07-10",
    },
  },
  {
    slug: "gapyeong-forest-house",
    title: "숲 전망이 있는 모던 하우스",
    summary: "큰 창으로 숲을 마주하는 가족 여행용 스테이",
    location: "가평군, 경기도",
    city: "가평군",
    district: "경기도",
    country: "대한민국",
    distance: "아침고요수목원까지 차로 16분",
    pricePerNight: 176000,
    rating: 4.88,
    reviewCount: 142,
    badge: "신규",
    gradient: "linear-gradient(135deg, #a7d7c5 0%, #f2f7e8 100%)",
    category: "숲",
    maxGuests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    petFriendly: true,
    keywords: ["가평", "숲", "전망", "근교", "경기도", "가족"],
    availability: {
      startDate: "2026-04-20",
      endDate: "2026-08-01",
    },
  },
  {
    slug: "yangpyeong-window-cabin",
    title: "통창 거실이 있는 감성 오두막",
    summary: "벽난로와 숲 향이 어울리는 주말용 캐빈",
    location: "양평군, 경기도",
    city: "양평군",
    district: "경기도",
    country: "대한민국",
    distance: "두물머리까지 차로 19분",
    pricePerNight: 203000,
    rating: 4.9,
    reviewCount: 158,
    badge: "슈퍼호스트",
    gradient: "linear-gradient(135deg, #d5c4f1 0%, #fce8df 100%)",
    category: "오두막",
    maxGuests: 5,
    bedrooms: 2,
    beds: 3,
    baths: 2,
    petFriendly: false,
    keywords: ["양평", "오두막", "감성", "숲", "경기도", "통창"],
    availability: {
      startDate: "2026-05-01",
      endDate: "2026-07-31",
    },
  },
  {
    slug: "jeju-tangerine-mini-house",
    title: "제주 감귤밭 옆 미니 하우스",
    summary: "귤밭 산책과 조용한 아침이 있는 제주 스테이",
    location: "제주시, 제주도",
    city: "제주시",
    district: "제주도",
    country: "대한민국",
    distance: "공항에서 차로 18분",
    pricePerNight: 139000,
    rating: 4.97,
    reviewCount: 231,
    badge: "게스트 선호",
    gradient: "linear-gradient(135deg, #ffd166 0%, #fff0c1 100%)",
    category: "농장",
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    petFriendly: false,
    keywords: ["제주", "감귤밭", "제주시", "제주도", "커플", "자연"],
    availability: {
      startDate: "2026-04-20",
      endDate: "2026-09-10",
    },
  },
  {
    slug: "gangneung-terrace-stay",
    title: "바다 앞 테라스 스테이",
    summary: "해변 산책과 브런치를 즐기기 좋은 오션뷰 숙소",
    location: "강릉시, 강원도",
    city: "강릉시",
    district: "강원도",
    country: "대한민국",
    distance: "해변까지 도보 3분",
    pricePerNight: 212000,
    rating: 4.86,
    reviewCount: 165,
    badge: "바다 전망",
    gradient: "linear-gradient(135deg, #8ecae6 0%, #e0fbfc 100%)",
    category: "호수 근처",
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    petFriendly: true,
    keywords: ["강릉", "바다", "강원도", "테라스", "해변", "오션뷰"],
    availability: {
      startDate: "2026-04-24",
      endDate: "2026-08-20",
    },
  },
  {
    slug: "seorak-lake-house",
    title: "호수 옆 우드톤 패밀리 하우스",
    summary: "아이들과 머물기 좋은 넓은 거실의 가족형 숙소",
    location: "속초시, 강원도",
    city: "속초시",
    district: "강원도",
    country: "대한민국",
    distance: "영랑호까지 도보 6분",
    pricePerNight: 198000,
    rating: 4.91,
    reviewCount: 119,
    badge: "가족 인기",
    gradient: "linear-gradient(135deg, #7cc6fe 0%, #f9f871 100%)",
    category: "호수 근처",
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    baths: 2,
    petFriendly: false,
    keywords: ["속초", "호수", "강원도", "가족", "영랑호", "우드톤"],
    availability: {
      startDate: "2026-05-05",
      endDate: "2026-09-01",
    },
  },
  {
    slug: "busan-cliff-view-villa",
    title: "절벽 전망 오션 빌라",
    summary: "프라이빗 자쿠지와 넓은 데크가 있는 남해안 숙소",
    location: "부산, 기장군",
    city: "부산",
    district: "기장군",
    country: "대한민국",
    distance: "해동용궁사까지 차로 9분",
    pricePerNight: 246000,
    rating: 4.92,
    reviewCount: 143,
    badge: "인기 급상승",
    gradient: "linear-gradient(135deg, #55c1ff 0%, #f4e1d2 100%)",
    category: "전망 좋은 숙소",
    maxGuests: 5,
    bedrooms: 2,
    beds: 3,
    baths: 2,
    petFriendly: true,
    keywords: ["부산", "기장", "바다", "오션뷰", "자쿠지", "전망"],
    availability: {
      startDate: "2026-04-21",
      endDate: "2026-08-31",
    },
  },
];

export default stays;
