import 'dotenv/config'
import mongoose from 'mongoose'
import connectDB from '../src/config/db.js'
import Accommodation from '../src/models/accommodation.model.js'

const dummyAccommodations = [
  {
    title: '관악산 뷰 프라이빗 룸',
    description: '관악산이 한눈에 보이는 조용한 숙소입니다.',
    location: { city: '서울', region: '관악구', fullAddress: '서울특별시 관악구 신림동' },
    pricePerNight: 85000,
    maxGuests: 2,
    rating: 4.92,
    reviewCount: 128,
    images: ['https://picsum.photos/seed/room1/400/380'],
    amenities: ['WiFi', '주방', '에어컨'],
    isSuperhost: true,
  },
  {
    title: '신림동 아늑한 원룸',
    description: '혼자 여행하기 좋은 작은 원룸.',
    location: { city: '서울', region: '관악구', fullAddress: '서울특별시 관악구 신림동' },
    pricePerNight: 55000,
    maxGuests: 2,
    rating: 4.81,
    reviewCount: 64,
    images: ['https://picsum.photos/seed/room2/400/380'],
    amenities: ['WiFi', '세탁기'],
    isSuperhost: false,
  },
  {
    title: '봉천동 모던 스튜디오',
    description: '깔끔한 인테리어의 스튜디오.',
    location: { city: '서울', region: '관악구', fullAddress: '서울특별시 관악구 봉천동' },
    pricePerNight: 72000,
    maxGuests: 3,
    rating: 4.75,
    reviewCount: 92,
    images: ['https://picsum.photos/seed/room3/400/380'],
    amenities: ['WiFi', '주방', 'TV'],
    isSuperhost: false,
  },
  {
    title: '서울대입구역 근처 복층',
    description: '교통이 편리한 복층 구조 숙소.',
    location: { city: '서울', region: '관악구', fullAddress: '서울특별시 관악구 봉천동' },
    pricePerNight: 110000,
    maxGuests: 4,
    rating: 4.97,
    reviewCount: 212,
    images: ['https://picsum.photos/seed/room4/400/380'],
    amenities: ['WiFi', '주방', '세탁기', '주차장'],
    isSuperhost: true,
  },
  {
    title: '해운대 오션뷰 아파트',
    description: '바다가 보이는 해운대 숙소.',
    location: { city: '부산', region: '해운대구', fullAddress: '부산광역시 해운대구' },
    pricePerNight: 150000,
    maxGuests: 4,
    rating: 4.89,
    reviewCount: 305,
    images: ['https://picsum.photos/seed/room5/400/380'],
    amenities: ['WiFi', '수영장', '주방'],
    isSuperhost: true,
  },
  {
    title: '광안리 루프탑 하우스',
    description: '광안대교 야경을 즐길 수 있는 숙소.',
    location: { city: '부산', region: '수영구', fullAddress: '부산광역시 수영구' },
    pricePerNight: 130000,
    maxGuests: 6,
    rating: 4.86,
    reviewCount: 178,
    images: ['https://picsum.photos/seed/room6/400/380'],
    amenities: ['WiFi', '루프탑', '주방'],
    isSuperhost: false,
  },
  {
    title: '제주 서귀포 풀빌라',
    description: '프라이빗 수영장이 있는 감성 풀빌라.',
    location: { city: '제주', region: '서귀포시', fullAddress: '제주특별자치도 서귀포시' },
    pricePerNight: 240000,
    maxGuests: 6,
    rating: 4.95,
    reviewCount: 421,
    images: ['https://picsum.photos/seed/room7/400/380'],
    amenities: ['수영장', 'WiFi', '바비큐'],
    isSuperhost: true,
  },
  {
    title: '제주 애월 바다 전망 독채',
    description: '애월 해변 근처의 조용한 독채.',
    location: { city: '제주', region: '제주시', fullAddress: '제주특별자치도 제주시 애월읍' },
    pricePerNight: 180000,
    maxGuests: 4,
    rating: 4.83,
    reviewCount: 267,
    images: ['https://picsum.photos/seed/room8/400/380'],
    amenities: ['WiFi', '주방', '테라스'],
    isSuperhost: false,
  },
  {
    title: '강릉 경포대 해변 펜션',
    description: '경포대 해변까지 도보 5분.',
    location: { city: '강릉', region: '강원도', fullAddress: '강원도 강릉시 경포동' },
    pricePerNight: 120000,
    maxGuests: 5,
    rating: 4.78,
    reviewCount: 156,
    images: ['https://picsum.photos/seed/room9/400/380'],
    amenities: ['WiFi', '주방', '주차장'],
    isSuperhost: false,
  },
  {
    title: '경주 한옥 스테이',
    description: '고즈넉한 한옥에서의 하룻밤.',
    location: { city: '경주', region: '경상북도', fullAddress: '경상북도 경주시 황남동' },
    pricePerNight: 140000,
    maxGuests: 4,
    rating: 4.91,
    reviewCount: 189,
    images: ['https://picsum.photos/seed/room10/400/380'],
    amenities: ['WiFi', '한옥', '마당'],
    isSuperhost: true,
  },
  {
    title: '여수 밤바다 오션뷰',
    description: '여수 밤바다를 한눈에 담는 숙소.',
    location: { city: '여수', region: '전라남도', fullAddress: '전라남도 여수시' },
    pricePerNight: 135000,
    maxGuests: 4,
    rating: 4.87,
    reviewCount: 234,
    images: ['https://picsum.photos/seed/room11/400/380'],
    amenities: ['WiFi', '오션뷰', '주방'],
    isSuperhost: true,
  },
  {
    title: '속초 설악산 전망 펜션',
    description: '설악산이 보이는 조용한 펜션.',
    location: { city: '속초', region: '강원도', fullAddress: '강원도 속초시' },
    pricePerNight: 98000,
    maxGuests: 3,
    rating: 4.72,
    reviewCount: 87,
    images: ['https://picsum.photos/seed/room12/400/380'],
    amenities: ['WiFi', '주차장'],
    isSuperhost: false,
  },
  {
    title: '전주 한옥마을 게스트하우스',
    description: '한옥마을 도보권의 전통 게스트하우스.',
    location: { city: '전주', region: '전라북도', fullAddress: '전라북도 전주시 풍남동' },
    pricePerNight: 75000,
    maxGuests: 2,
    rating: 4.79,
    reviewCount: 142,
    images: ['https://picsum.photos/seed/room13/400/380'],
    amenities: ['WiFi', '한옥'],
    isSuperhost: false,
  },
  {
    title: '양평 북한강 뷰 독채',
    description: '북한강이 보이는 힐링 독채.',
    location: { city: '양평', region: '경기도', fullAddress: '경기도 양평군' },
    pricePerNight: 170000,
    maxGuests: 5,
    rating: 4.84,
    reviewCount: 198,
    images: ['https://picsum.photos/seed/room14/400/380'],
    amenities: ['WiFi', '주방', '바비큐'],
    isSuperhost: true,
  },
  {
    title: '인천 송도 스카이뷰',
    description: '송도의 야경을 즐기는 고층 숙소.',
    location: { city: '인천', region: '연수구', fullAddress: '인천광역시 연수구 송도동' },
    pricePerNight: 115000,
    maxGuests: 4,
    rating: 4.76,
    reviewCount: 103,
    images: ['https://picsum.photos/seed/room15/400/380'],
    amenities: ['WiFi', '주방', '피트니스'],
    isSuperhost: false,
  },
  {
    title: '제주 협재 비치 하우스',
    description: '협재 해수욕장 도보 3분 거리.',
    location: { city: '제주', region: '제주시', fullAddress: '제주특별자치도 제주시 한림읍' },
    pricePerNight: 195000,
    maxGuests: 6,
    rating: 4.93,
    reviewCount: 356,
    images: ['https://picsum.photos/seed/room16/400/380'],
    amenities: ['WiFi', '오션뷰', '주방'],
    isSuperhost: true,
  },
  {
    title: '부산 감천문화마을 숙소',
    description: '감천문화마을의 독특한 분위기.',
    location: { city: '부산', region: '사하구', fullAddress: '부산광역시 사하구 감천동' },
    pricePerNight: 88000,
    maxGuests: 3,
    rating: 4.71,
    reviewCount: 91,
    images: ['https://picsum.photos/seed/room17/400/380'],
    amenities: ['WiFi', '주방'],
    isSuperhost: false,
  },
  {
    title: '서울 홍대 감성 스테이',
    description: '홍대 중심가의 트렌디한 숙소.',
    location: { city: '서울', region: '마포구', fullAddress: '서울특별시 마포구 홍대' },
    pricePerNight: 125000,
    maxGuests: 3,
    rating: 4.82,
    reviewCount: 217,
    images: ['https://picsum.photos/seed/room18/400/380'],
    amenities: ['WiFi', 'TV', '에어컨'],
    isSuperhost: true,
  },
]

async function seed() {
  await connectDB()
  await Accommodation.deleteMany({})
  const inserted = await Accommodation.insertMany(dummyAccommodations)
  console.log(`Seeded ${inserted.length} accommodations`)
  await mongoose.disconnect()
}

seed().catch((err) => {
  console.error('Seed failed:', err)
  process.exit(1)
})
